config/routes.rb
VpsManage::Application.routes.draw do
  root :to => "virtual_environments#index"

  resources :projects

  resources :machines

  resources :virtual_environments

  match '*path', :to => 'application#render_404'

end

app/models/virtual_environment.rb
class VirtualEnvironment < ActiveRecord::Base
  belongs_to :machine
  has_many :virtual_environment_has_projects
  has_many :projects, :through => :virtual_environment_has_projects 

  validates_presence_of :name
  validates_numericality_of :tap, :vnc, :allow_blank => true
  validates_uniqueness_of :name, :ip, :mac, :allow_blank => true
  validate :check_vnc
  #validates_date :expired_at#, :allow_blank => true

  attr_accessible :image_name, :ip, :mac, :machine_id, :name, :note, :tap, :vnc, :contact, :expired_at

  def self.per_page
    10
  end

  def add_project(project_ids)
    self.projects = []
    project_ids.each do |id|
      self.projects << Project.find(id) rescue nil
    end if project_ids
  end

  def check_vnc
   return unless vnc
   return unless machine_id

   before_virtual_environment = VirtualEnvironment.find(self.id) rescue nil
   if before_virtual_environment
     before_vnc = before_virtual_environment.vnc
     before_machine_id = before_virtual_environment.machine_id
     return if before_vnc == vnc and before_machine_id == machine_id
   end

   errors.add(:vnc, I18n.t('errors.messages.taken')) if VirtualEnvironment.where(:machine_id => machine_id, :vnc => vnc).first
  end
end

app/controllers/virtual_environments_controller.rb
class VirtualEnvironmentsController < ApplicationController

  def index
    sort = {:sort_by => 'created_at', :order => 'asc'}
    case params[:sort_by]
    when 'name'
      sort[:sort_by] = 'name'
    when 'machine'
      sort[:sort_by] = 'machine_id'
    when 'ip'
      sort[:sort_by] = 'ip'
    when 'tap'
      sort[:sort_by] = 'tap'
    when 'mac'
      sort[:sort_by] = 'mac'
    when 'vnc'
      sort[:sort_by] = 'vnc'
    when 'image_name'
      sort[:sort_by] = 'image_name'
    when 'expired_at'
      sort[:sort_by] = 'expired_at'
    end

    case params[:order]
    when 'asc'
      sort[:order] = 'asc'
    when 'desc'
      sort[:order] = 'desc'
    end

    @virtual_environments = VirtualEnvironment.order("#{sort[:sort_by]} #{sort[:order]}").page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @virtual_environments }
    end
  end

  def show
    @virtual_environment = VirtualEnvironment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @virtual_environment }
    end
  end

  def new
    @virtual_environment = VirtualEnvironment.new
    @project_ids = []
    prepare_options

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @virtual_environment }
    end
  end

  def edit
    @virtual_environment = VirtualEnvironment.find(params[:id])
    @project_ids = @virtual_environment.projects.inject([]){ |ids, project| ids << project.id.to_i } rescue []
    prepare_options
  end

  def create
    @virtual_environment = VirtualEnvironment.new(params[:virtual_environment])
    @project_ids = params[:projects] ? params[:projects].inject([]){|ids, id| ids << id.to_i} : []

    respond_to do |format|
      begin
        ActiveRecord::Base.transaction do
          @virtual_environment.save!
          @virtual_environment.add_project(@project_ids)
          format.html { redirect_to @virtual_environment, notice: t('controller.successfully_created', :model => t('activerecord.models.virtual_environment')) }
          format.json { render json: @virtual_environment, status: :created, location: @virtual_environment }
        end
      rescue
        prepare_options
        format.html { render action: "new" }
        format.json { render json: @virtual_environment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @virtual_environment = VirtualEnvironment.find(params[:id])
    @project_ids = params[:projects] ? params[:projects].inject([]){|ids, id| ids << id.to_i} :[]
    
    respond_to do |format|
      begin
        ActiveRecord::Base.transaction do
          @virtual_environment.update_attributes!(params[:virtual_environment])
          @virtual_environment.add_project(@project_ids)
          format.html { redirect_to @virtual_environment, notice: t('controller.successfully_updated', :model => t('activerecord.models.virtual_environment')) }
          format.json { head :no_content }
        end
      rescue
        prepare_options
        format.html { render action: "edit" }
        format.json { render json: @virtual_environment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @virtual_environment = VirtualEnvironment.find(params[:id])
    @virtual_environment.destroy

    respond_to do |format|
      format.html { redirect_to virtual_environments_url, notice: t('controller.successfully_deleted', :model => t('activerecord.models.virtual_environment')) }
      format.json { head :no_content }
    end
  end

  private
  def prepare_options
    @machines = Machine.all
    @projects = Project.all
  end
end

app/helpers/virtual_environments_helper.rb
module VirtualEnvironmentsHelper
end

app/views/virtual_environments/_form.html.erb
<%= form_for(@virtual_environment) do |f| %>

  <div style="float:left; padding-right: 100px;">
    <div class="field" style="">
      <%= f.label :name %><abbr id="required">*</abbr><br />
      <%= f.text_field :name %>
      <%= error_message_on(:virtual_environment, :name, t('activerecord.attributes.virtual_environment.name')) %>
    </div>
    <div class="field">
      <%= f.label t('activerecord.attributes.machine.name') %><br />
      <%= f.select(:machine_id, @machines.collect{|machine| [machine.name, machine.id]}, :include_blank => true) %>
      <%= error_message_on(:virtual_environment, :machine_id, t('activerecord.attributes.machine.name')) %>
    </div>
    <div class="field">
      <%= f.label :ip %><br />
      <%= f.text_field :ip %>
      <%= error_message_on(:virtual_environment, :ip, t('activerecord.attributes.virtual_environment.ip')) %>
    </div>
    <div class="field">
      <%= f.label :tap %><br />
      <%= f.text_field :tap %>
      <%= error_message_on(:virtual_environment, :tap, t('activerecord.attributes.virtual_environment.tap')) %>
    </div>
    <div class="field">
      <%= f.label :mac %><br />
      <%= f.text_field :mac %>
      <%= error_message_on(:virtual_environment, :mac, t('activerecord.attributes.virtual_environment.mac')) %>
    </div>
    <div class="field">
      <%= f.label :vnc %><br />
      <%= f.text_field :vnc %>
      <%= error_message_on(:virtual_environment, :vnc, t('activerecord.attributes.virtual_environment.vnc')) %>
    </div>
    <div class="field">
      <%= f.label :image_name %><br />
      <%= f.text_field :image_name %>
      <%= error_message_on(:virtual_environment, :image_name, t('activerecord.attributes.virtual_environment.image_name')) %>
    </div>
    <div class="field">
      <%= f.label :contact %><br />
      <%= f.text_field :contact %>
      <%= error_message_on(:virtual_environment, :contact, t('activerecord.attributes.virtual_environment.contact')) %>
    </div>
    <div class="field">
      <%= f.label :expired_at %><br />
      <% unless @virtual_environment.expired_at %>
        <%= f.text_field :expired_at, :placeholder => "#{t('page.example')}: #{t('page.example_date')}", :class => 'date_field' %>
      <% else %>
        <%= f.text_field :expired_at, :value => @virtual_environment.expired_at.strftime('%Y-%m-%d'), :placeholder => "#{t('page.example')}: #{t('page.example_date')}", :class => 'date_field' %>
      <% end %>
      <%= error_message_on(:virtual_environment, :expired_at, t('activerecord.attributes.virtual_environment.expired_at')) %>
    </div>
  </div>

  <div>
    <div class="field">
      <%= f.label t('activerecord.models.project') %><br />
      <% @projects.each do |project| %>
        <%= check_box_tag "projects[]", project.id, @project_ids.index(project.id) ? true : false %><%= project.name %><br />
      <% end %>
    </div>
  </div>
  <br style="clear:both;" />

  <div>
    <div class="field">
      <%= f.label :note %><br />
      <%= f.text_area :note %>
      <%= error_message_on(:virtual_environment, :note, t('activerecord.attributes.virtual_environment.note')) %>
    </div>
    <div class="actions">
      <%= f.submit :disable_with => t('page.wait') %>
    </div>
  </div>
<% end %>

app/views/virtual_environments/_virtual_environment_list.html.erb
<div>
  <b><%= t('page.listing', :model => t('activerecord.models.virtual_environment')) -%></b>
  <table class="index">
    <%- virtual_environments.each do |virtual_environment| -%>
      <tr class="line<%= cycle("0", "1") -%>">
        <td><%= link_to virtual_environment.name, virtual_environment %></td>
      </tr>
    <%- end -%>
  </table>
</div>

app/views/virtual_environments/edit.html.erb
<div id="content_detail">
  <h4 id="page_title"><%= t('page.editing', :model => t('activerecord.models.virtual_environment')) %></h4>
  <%= render 'form' %>
</div>

<div id="submenu">
  <ul>
    <li><%= link_to t('page.showing', :model => t('activerecord.models.virtual_environment')), @virtual_environment %></li>
    <li><%= link_to t('page.listing', :model => t('activerecord.models.virtual_environment')), virtual_environments_path %></li>
  </ul>
</div>

app/views/virtual_environments/index.html.erb
<div id="content_detail">
  <h4 id="page_title"><%= t('page.listing', :model => t('activerecord.models.virtual_environment')) %></h5>
  <p id="notice"><%= notice %></p>

  <div id="content_list">
    <table class="index">
      <tr>
        <th>
          <% if params[:sort_by] == 'name' and params[:order] == 'asc' %>
            <%= link_to t('activerecord.attributes.virtual_environment.name'), params.merge(:sort_by => 'name', :order => 'desc') %>
          <% else %>
            <%= link_to t('activerecord.attributes.virtual_environment.name'), params.merge(:sort_by => 'name', :order => 'asc') %>
          <% end %>
        </th>
        <th>
          <% if params[:sort_by] == 'machine' and params[:order] == 'asc'%>
            <%= link_to t('activerecord.models.machine'), params.merge(:sort_by => 'machine', :order => 'desc') %>
          <% else %>
            <%= link_to t('activerecord.models.machine'), params.merge(:sort_by => 'machine', :order => 'asc') %>
          <% end %>
        </th>
        <th>
          <% if params[:sort_by] == 'ip' and params[:order] == 'asc' %>
            <%= link_to t('activerecord.attributes.virtual_environment.ip'), params.merge(:sort_by => 'ip', :order => 'desc') %>
          <% else %>
            <%= link_to t('activerecord.attributes.virtual_environment.ip'), params.merge(:sort_by => 'ip', :order => 'asc') %>
          <% end %>
        </th>
        <th>
          <% if params[:sort_by] == 'tap' and params[:order] == 'asc' %>
            <%= link_to t('activerecord.attributes.virtual_environment.tap'), params.merge(:sort_by => 'tap', :order => 'desc') %>
          <% else %>
            <%= link_to t('activerecord.attributes.virtual_environment.tap'), params.merge(:sort_by => 'tap', :order => 'asc') %>
          <% end %>
        </th>
        <th>
          <% if params[:sort_by] == 'mac' and params[:order] == 'asc' %>
            <%= link_to t('activerecord.attributes.virtual_environment.mac'), params.merge(:sort_by => 'mac', :order => 'desc') %>
          <% else %>
            <%= link_to t('activerecord.attributes.virtual_environment.mac'), params.merge(:sort_by => 'mac', :order => 'asc') %>
          <% end %>
        </th>
        <th>
          <% if params[:sort_by] == 'vnc' and params[:order] == 'asc' %>
            <%= link_to t('activerecord.attributes.virtual_environment.vnc'), params.merge(:sort_by => 'vnc', :order => 'desc') %>
          <% else %>
            <%= link_to t('activerecord.attributes.virtual_environment.vnc'), params.merge(:sort_by => 'vnc', :order => 'asc') %>
          <% end %>
        </th>
        <th>
          <% if params[:sort_by] == 'image_name' and params[:order] == 'asc' %>
            <%= link_to t('activerecord.attributes.virtual_environment.image_name'), params.merge(:sort_by => 'image_name', :order => 'desc') %>
          <% else %>
            <%= link_to t('activerecord.attributes.virtual_environment.image_name'), params.merge(:sort_by => 'image_name', :order => 'asc') %>
          <% end %>
        </th>
        <th>
          <% if params[:sort_by] == 'expired_at' and params[:order] == 'asc' %>
            <%= link_to t('activerecord.attributes.virtual_environment.expired_at'), params.merge(:sort_by => 'expired_at', :order => 'desc') %>
          <% else %>
            <%= link_to t('activerecord.attributes.virtual_environment.expired_at'), params.merge(:sort_by => 'expired_at', :order => 'asc') %>
          <% end %>
        </th>
        <th class="action_column"></th>
      </tr>

      <% @virtual_environments.each do |virtual_environment| %>
        <tr class="line<%= cycle("0", "1") -%>">
          <td><%= link_to virtual_environment.name, virtual_environment %></td>
          <td><%= link_to virtual_environment.machine.name, virtual_environment.machine if virtual_environment.machine %></td>
          <td><%= virtual_environment.ip %></td>
          <td><%= virtual_environment.tap %></td>
          <td><%= virtual_environment.mac %></td>
          <td><%= virtual_environment.vnc %></td>
          <td><%= virtual_environment.image_name %></td>
          <td><%= l(virtual_environment.expired_at, :format => :only_date) if virtual_environment.expired_at %></td>  
          <td>
            <%= link_to image_tag('paperpencil32.png', :size => '16x16', :alt => t('page.edit'), :title => t('page.edit')), edit_virtual_environment_path(virtual_environment) %>
            <%= link_to image_tag('stop32.png', :size => '16x16', :alt => t('page.destroy'), :title => t('page.destroy')), virtual_environment, confirm: t('page.are_you_sure'), method: :delete %>
          </td>
        </tr>
      <% end %>
    </table>
    <br />
    <%= will_paginate @virtual_environments, :previous_label=>'<', :next_label=>'>' %>
</div>
</div>

<div id="submenu">
  <ul>
    <li><%= link_to t('page.new', :model => t('activerecord.models.virtual_environment')), new_virtual_environment_path %></li>
  </ul>
</div>

app/views/virtual_environments/new.html.erb
<div id="content_detail">
  <h4 id="page_title"><%= t('page.new', :model => t('activerecord.models.virtual_environment')) -%></h4>
  <%= render 'form' %>
</div>

<div id="submenu">
  <ul>
    <li><%= link_to t('page.listing', :model => t('activerecord.models.virtual_environment')), virtual_environments_path %></li>
  </ul>
</div>

app/views/virtual_environments/show.html.erb
<div id="content_detail">
<h4 id="page_title"><%= t('page.showing', :model => t('activerecord.models.virtual_environment')) %></h4>
<p id="notice"><%= notice %></p>

<p>
  <b><%= t('activerecord.attributes.virtual_environment.name') %>:</b>
  <%= @virtual_environment.name %>
</p>

<p>
  <b><%= t('activerecord.models.machine') %>:</b>
  <%= link_to @virtual_environment.machine.name, @virtual_environment.machine if @virtual_environment.machine %>
</p>

<p>
  <b><%= t('activerecord.attributes.virtual_environment.ip') %>:</b>
  <%= @virtual_environment.ip %>
</p>

<p>
  <b><%= t('activerecord.attributes.virtual_environment.tap') %>:</b>
  <%= @virtual_environment.tap %>
</p>

<p>
  <b><%= t('activerecord.attributes.virtual_environment.mac') %>:</b>
  <%= @virtual_environment.mac %>
</p>

<p>
  <b><%= t('activerecord.attributes.virtual_environment.vnc') %>:</b>
  <%= @virtual_environment.vnc %>
</p>

<p>
  <b><%= t('activerecord.attributes.virtual_environment.image_name') %>:</b>
  <%= @virtual_environment.image_name %>
</p>

<p>
  <b><%= t('activerecord.attributes.virtual_environment.note') %>:</b>
  <%= @virtual_environment.note %>
</p>

<p>
  <b><%= t('activerecord.attributes.virtual_environment.contact') %>:</b>
  <%= @virtual_environment.contact %>
</p>

<p>
  <b><%= t('activerecord.attributes.virtual_environment.expired_at') %>:</b>
  <%= l(@virtual_environment.expired_at, :format => :only_date) if @virtual_environment.expired_at %>
</p>

<p>
  <b><%= t('page.created_at') %>:</b>
  <%= l(@virtual_environment.created_at) %>
</p>

<p>
  <b><%= t('page.updated_at') %>:</b>
  <%= l(@virtual_environment.updated_at) %>
</p>

<br />
<%= render 'projects/project_list', :projects => @virtual_environment.projects %>
</div>

<div id="submenu">
  <ul>
    <li><%= link_to t('page.new', :model => t('activerecord.models.virtual_environment')), new_virtual_environment_path %></li>
    <li><%= link_to t('page.editing', :model => t('activerecord.models.virtual_environment')), edit_virtual_environment_path(@virtual_environment) %></li>
    <li><%= link_to t('page.listing', :model => t('activerecord.models.virtual_environment')), virtual_environments_path %></li>
  </ul>
</div>