config/routes.rb
VpsManage::Application.routes.draw do
  root :to => "virtual_environments#index"

  resources :projects

  resources :machines

  resources :virtual_environments

  match '*path', :to => 'application#render_404'

end

app/models/machine.rb
class Machine < ActiveRecord::Base
  has_many :virtual_environments

  validates_presence_of :name
  validates_uniqueness_of :name

  attr_accessible :memory, :name, :note, :cpu

  def self.per_page
    10
  end

  def destroy?
    return false if self.virtual_environments.size > 0
    true
  end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  # GET /machines
  # GET /machines.json
  def index
    sort = {:sort_by => 'created_at', :order => 'asc'}
    case params[:sort_by]
    when 'name'
      sort[:sort_by] = 'name'
    when 'cpu'
      sort[:sort_by] = 'cpu'
    when 'memory'
      sort[:sort_by] = 'memory'
    end    

    case params[:order]
    when 'asc'
      sort[:order] = 'asc'
    when 'desc'
      sort[:order] = 'desc'
    end

    @machines = Machine.order("#{sort[:sort_by]} #{sort[:order]}").page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @machines }
    end
  end

  # GET /machines/1
  # GET /machines/1.json
  def show
    @machine = Machine.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @machine }
    end
  end

  # GET /machines/new
  # GET /machines/new.json
  def new
    @machine = Machine.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @machine }
    end
  end

  # GET /machines/1/edit
  def edit
    @machine = Machine.find(params[:id])
  end

  # POST /machines
  # POST /machines.json
  def create
    @machine = Machine.new(params[:machine])

    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine, notice: t('controller.successfully_created', :model => t('activerecord.models.machine')) }
        format.json { render json: @machine, status: :created, location: @machine }
      else
        format.html { render action: "new" }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /machines/1
  # PUT /machines/1.json
  def update
    @machine = Machine.find(params[:id])

    respond_to do |format|
      if @machine.update_attributes(params[:machine])
        format.html { redirect_to @machine, notice: t('controller.successfully_updated', :model => t('activerecord.models.machine')) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /machines/1
  # DELETE /machines/1.json
  def destroy
    @machine = Machine.find(params[:id])
    @machine.destroy

    respond_to do |format|
      format.html { redirect_to machines_url, notice: t('controller.successfully_deleted', :model => t('activerecord.models.machine')) }
      format.json { head :no_content }
    end
  end
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/views/machines/_form.html.erb
<%= form_for(@machine) do |f| %>

  <div class="field">
    <%= f.label :name %><abbr id="required">*</abbr><br />
    <%= f.text_field :name %>
    <%= error_message_on(:machine, :name, t('activerecord.attributes.machine.name')) %>
  </div>
  <div class="field">
    <%= f.label :cpu %><br />
    <%= f.text_field :cpu %>
    <%= error_message_on(:machine, :cpu, t('activerecord.attributes.machine.cpu')) %>
  </div>
  <div class="field">
    <%= f.label :memory %><br />
    <%= f.text_field :memory %>
    <%= error_message_on(:machine, :memory, t('activerecord.attributes.machine.memory')) %>
  </div>
  <div class="field">
    <%= f.label :note %><br />
    <%= f.text_area :note %>
    <%= error_message_on(:machine, :note, t('activerecord.attributes.machine.note')) %>
  </div>
  <div class="actions">
    <%= f.submit :disable_with => t('page.wait') %>
  </div>
<% end %>

app/views/machines/edit.html.erb
<div id="content_detail">
  <h4 id="page_title"><%= t('page.editing', :model => t('activerecord.models.machine')) -%></h4>
  <%= render 'form' %>
</div>

<div id="submenu">
  <ul>
    <li><%= link_to t('page.showing', :model => t('activerecord.models.machine')), @machine %></li>
    <li><%= link_to t('page.listing', :model => t('activerecord.models.machine')), machines_path %></li>
  </ul>
</div>

app/views/machines/index.html.erb
<div id="content_detail">
  <h4 id="page_title"><%= t('page.listing', :model => t('activerecord.models.machine')) %></h4>
  <p id="notice"><%= notice %></p>

  <div id="content_list">
    <table class="index">
      <tr>
        <th>
          <% if params[:sort_by] == 'name' and params[:order] == 'asc'%>
            <%= link_to t('activerecord.attributes.machine.name'), params.merge(:sort_by => 'name', :order => 'desc') %>
          <% else%>
            <%= link_to t('activerecord.attributes.machine.name'), params.merge(:sort_by => 'name', :order => 'asc') %>
          <% end %>
        </th>
        <th>
          <% if params[:sort_by] == 'cpu' and params[:order] == 'asc'%>
            <%= link_to t('activerecord.attributes.machine.cpu'), params.merge(:sort_by => 'cpu', :order => 'desc') %>
          <% else %>
            <%= link_to t('activerecord.attributes.machine.cpu'), params.merge(:sort_by => 'cpu', :order => 'asc') %>
          <% end %>
        </th>
        <th>
          <% if params[:sort_by] == 'memory' and params[:order] == 'asc'%>
            <%= link_to t('activerecord.attributes.machine.memory'), params.merge(:sort_by => 'memory', :order => 'desc') %>
          <% else %>
            <%= link_to t('activerecord.attributes.machine.memory'), params.merge(:sort_by => 'memory', :order => 'asc') %>
          <% end %>
        </th>
        <th class="action_column"></th>
      </tr>

      <% @machines.each do |machine| %>
        <tr class="line<%= cycle("0", "1") -%>">
          <td><%=link_to machine.name, machine %></td>
          <td><%= machine.cpu %></td>
          <td><%= machine.memory %></td>
          <td>
            <%= link_to image_tag('paperpencil32.png', :size => '16x16', :alt => t('page.edit'), :title => t('page.edit')), edit_machine_path(machine) %>
            <%= link_to image_tag('stop32.png', :size => '16x16', :alt => t('page.destroy'), :title => t('page.destroy')), machine, confirm: t('page.are_you_sure'), method: :delete if machine.destroy? %>
          </td>
        </tr>
      <% end %>
    </table>
    <br />
    <%= will_paginate @diaries, :previous_label=>'<', :next_label=>'>' %> 
  </div>
</div>

<div id="submenu">
  <ul>
    <li><%= link_to t('page.new', :model => t('activerecord.models.machine')), new_machine_path %></li>
  </ul>
</div>

app/views/machines/new.html.erb
<div id="content_detail">
  <h4 id="page_title"><%= t('page.new', :model => t('activerecord.models.machine')) -%></h4>
  <%= render 'form' %>
</div>

<div id="submenu">
  <ul>
    <li><%= link_to t('page.listing', :model => t('activerecord.models.machine')), machines_path %></li>
  </ul>
</div>

app/views/machines/show.html.erb
<div id="content_detail">
<h4 id="page_title"><%= t('page.showing', :model => t('activerecord.models.machine')) %></h4>
<p id="notice"><%= notice %></p>

<p>
  <b><%= t('activerecord.attributes.machine.name') %>:</b>
  <%= @machine.name %>
</p>

<p>
  <b><%= t('activerecord.attributes.machine.cpu') %>:</b>
  <%= @machine.cpu %>
</p>

<p>
  <b><%= t('activerecord.attributes.machine.memory') %>:</b>
  <%= @machine.memory %>
</p>

<p>
  <b><%= t('activerecord.attributes.machine.note') %>:</b>
  <%= @machine.note %>
</p>

<br />
<%= render 'virtual_environments/virtual_environment_list', :virtual_environments => @machine.virtual_environments %>
</div>

<div id="submenu">
  <ul>
    <li><%= link_to t('page.new', :model => t('activerecord.models.machine')), new_machine_path %></li>
    <li><%= link_to t('page.editing', :model => t('activerecord.models.machine')), edit_machine_path(@machine) %></li>
    <% if @machine.destroy? %>
      <li><%= link_to t('page.deleting', :model => t('activerecord.models.machine')), @machine, confirm: t('page.are_you_sure'), method: :delete %></li>
    <% end %>
    <li><%= link_to t('page.listing', :model => t('activerecord.models.machine')), machines_path %></li>
  </ul>
</div>